let state = null;
const view = document.getElementById('view');
const titles = {chat:'Chat del proyecto',overview:'Resumen del sistema',tasks:'Tareas de ingeniería',projects:'Proyectos conectados',activity:'Actividad del sistema'};
const esc = (value='') => String(value).replace(/[&<>"']/g, ch => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[ch]));
const ago = (date) => { const seconds = Math.max(0, (Date.now()-new Date(date))/1000); if(seconds<60)return 'ahora'; if(seconds<3600)return `hace ${Math.floor(seconds/60)} min`; return `hace ${Math.floor(seconds/3600)} h`; };
const projectName = id => state.projects.find(p=>p.id===id)?.name || 'Proyecto sin nombre';
function severityLabel(value){ return ({critical:'crítico',high:'alto',medium:'medio',info:'informativo'}[value]||value); }
function reviewPanel(t){
  const r=t.review;
  if(!r) return '';
  const findings=r.findings||[];
  return `<details class="review-panel" open><summary>Informe de revisión real · ${findings.length} hallazgo(s)</summary>
    <p class="review-summary">${esc(r.summary||t.result)}</p>
    <div class="review-meta"><span>Archivos inspeccionados: <strong>${r.inspectedFiles?.length||0}</strong></span><span>Rama: <strong>${esc(r.git?.branch||'no disponible')}</strong></span><span>Pruebas: <strong>${esc(r.tests?.status||'no ejecutadas')}</strong></span></div>
    <div class="finding-list">${findings.length?findings.map(f=>`<article class="finding ${esc(f.severity)}"><div class="finding-head"><span class="badge ${esc(f.severity)}">${esc(severityLabel(f.severity))}</span><strong>${esc(f.title)}</strong></div><p><b>Evidencia:</b> ${esc(f.evidence)}</p><p><b>Recomendación:</b> ${esc(f.recommendation)}</p></article>`).join(''):'<div class="empty">No se detectaron hallazgos en las comprobaciones disponibles.</div>'}</div>
    <div class="review-evidence"><b>Documentos:</b> ${r.inspectedDocuments?.map(esc).join(', ')||'ninguno'} · <b>Archivos cambiados:</b> ${r.git?.changedFiles?.length||0} · <b>Modificaciones:</b> ninguna</div>
  </details>`;
}
function taskRow(t){ return `<div class="task-row-wrap"><div class="task-row"><div><div class="task-title">${esc(t.title)}</div><div class="task-meta"><span class="badge ${t.status}">${esc(t.status)}</span><span>${t.kind==='review'?'Revisión del repositorio':esc(t.agent)}</span><span>·</span><span>${ago(t.updatedAt)}</span></div><div class="task-result">${esc(t.result||'Esperando ejecución...')}</div></div><div class="progress-wrap"><div class="progress"><i style="width:${t.progress||0}%"></i></div><div class="progress-label">${t.progress||0}%</div></div></div>${reviewPanel(t)}</div>`; }
function activityItem(e){ return `<div class="activity"><div class="activity-mark ${e.type}">${e.type==='success'?'✓':e.type==='agent'?'✦':'·'}</div><div><div class="activity-message">${esc(e.message)}</div><div class="activity-time">${ago(e.createdAt)}</div></div></div>`; }
function renderOverview(){ const running=state.tasks.filter(t=>t.status==='running').length, done=state.tasks.filter(t=>t.status==='completed').length; return `<div class="intro"><div><h2>Buenos días, administrador.</h2><p>Este es el estado de tu fábrica de software.</p></div><button class="primary" onclick="openTaskModal()">＋ Nueva tarea</button></div><div class="stats"><div class="card stat"><div class="stat-top">TAREAS TOTALES <span class="stat-icon blue">☷</span></div><div class="stat-number">${state.tasks.length}</div><div class="stat-foot">${done} completadas</div></div><div class="card stat"><div class="stat-top">EN EJECUCIÓN <span class="stat-icon purple">✦</span></div><div class="stat-number">${running}</div><div class="stat-foot">Worker local procesando</div></div><div class="card stat"><div class="stat-top">PROYECTOS <span class="stat-icon green">◈</span></div><div class="stat-number">${state.projects.length}</div><div class="stat-foot">Repositorios conectados</div></div><div class="card stat"><div class="stat-top">WORKER <span class="stat-icon orange">⌁</span></div><div class="stat-number" style="font-size:20px;margin-top:18px">ONLINE</div><div class="stat-foot">Último heartbeat ${ago(state.worker.lastHeartbeat)}</div></div></div><div class="grid"><section class="card section-card"><div class="section-head"><h3>Tareas recientes</h3><a onclick="navigate('tasks')">Ver todas →</a></div><div class="task-list">${state.tasks.slice(0,5).map(taskRow).join('')||'<div class="empty">Todavía no hay tareas.</div>'}</div></section><section class="card section-card"><div class="section-head"><h3>Actividad reciente</h3><a onclick="navigate('activity')">Ver todo →</a></div><div class="activity-list">${state.events.slice(0,5).map(activityItem).join('')}</div></section></div><section class="card section-card" style="margin-top:20px"><div class="section-head"><h3>Agentes del sistema</h3><a>Configuración →</a></div><div class="agents"><div class="agent"><div class="agent-head"><span class="agent-avatar blue">G</span><strong>GPT Architect</strong><span class="agent-status">ACTIVO</span></div><small>Arquitectura · planificación</small></div><div class="agent"><div class="agent-head"><span class="agent-avatar purple">C</span><strong>Claude Reviewer</strong><span class="agent-status">ACTIVO</span></div><small>Riesgos · revisión adversarial</small></div><div class="agent"><div class="agent-head"><span class="agent-avatar orange">A</span><strong>Antigravity</strong><span class="agent-status">PREPARADO</span></div><small>Ejecución · terminal · pruebas</small></div></div></section>`; }
function renderTasks(){ return `<div class="intro"><div><h2>Cola de ingeniería</h2><p>Las revisiones inspeccionan el proyecto sin modificarlo; las tareas de construcción siguen su flujo separado.</p></div><button class="primary" onclick="openTaskModal()">＋ Nueva solicitud</button></div><section class="card section-card"><div class="section-head"><h3>${state.tasks.length} solicitudes en este workspace</h3><span class="badge running">flujo supervisado</span></div><div class="task-list">${state.tasks.map(taskRow).join('')||'<div class="empty">Crea tu primera solicitud.</div>'}</div></section>`; }
function renderProjects(){ return `<div class="intro"><div><h2>Proyectos conectados</h2><p>GitHub y Git local quedan bajo el control del worker autorizado.</p></div><button class="primary" onclick="openProjectModal()">＋ Conectar proyecto</button></div><div class="project-grid">${state.projects.map(p=>`<div class="card project"><div class="stat-top"><span class="badge completed">conectado</span><span style="color:#19a66a">●</span></div><h3 style="margin-top:15px">${esc(p.name)}</h3><p>${esc(p.localPath)}</p><p>${esc(p.githubUrl||'GitHub no configurado')}</p><div class="project-footer"><span>rama ${esc(p.branch)}</span><span>worker local</span></div></div>`).join('')}</div>`; }
function renderActivity(){ return `<div class="intro"><div><h2>Actividad del sistema</h2><p>Registro de decisiones, agentes y ejecuciones.</p></div></div><section class="card section-card"><div class="activity-list">${state.events.map(activityItem).join('')}</div></section>`; }
function chatMessage(m){ const review=m.review; return `<article class="chat-message ${m.role}"><div class="chat-avatar">${m.role==='user'?'AN':'✦'}</div><div class="chat-bubble"><div class="chat-role">${m.role==='user'?'Tú':'Forge Control'}</div><div class="chat-content">${esc(m.content).replace(/\n\n/g,'</p><p>').replace(/^/,'<p>').replace(/$/,'</p>')}</div>${review?`<div class="chat-review"><strong>Informe de revisión</strong><span>${review.findings.length} hallazgo(s) · ${review.inspectedFiles.length} archivos · pruebas: ${esc(review.tests.status)}</span>${review.findings.slice(0,6).map(f=>`<div class="chat-finding ${esc(f.severity)}"><b>${esc(f.title)}</b><small>${esc(f.evidence)}</small></div>`).join('')}</div>`:''}</div></article>`; }
function renderChat(){ const messages=state.messages||[]; return `<div class="chat-layout"><section class="chat-card card"><div class="chat-head"><div><h2>Chat del proyecto</h2><p>Respuestas basadas en el repositorio seleccionado. Las revisiones son solo lectura.</p></div><span class="badge completed">worker local online</span></div><div id="chat-messages" class="chat-messages">${messages.length?messages.map(chatMessage).join(''):`<div class="chat-empty"><div class="chat-empty-icon">✦</div><h3>¿Qué quieres revisar?</h3><p>Pregunta por el estado del sistema o escribe “Revisa el proyecto”.</p><button class="secondary" onclick="usePrompt('Revisa el sistema y dime qué problemas tiene')">Revisar el sistema</button></div>`}</div><form class="chat-composer" onsubmit="sendChat(event)"><textarea name="message" rows="2" placeholder="Escribe una instrucción… (Enter para enviar, Shift+Enter para salto de línea)" required></textarea><button class="primary">Enviar</button></form></section><aside class="chat-context card"><h3>Contexto activo</h3><div class="context-project"><strong>${esc(state.projects[0]?.name||'Sin proyecto')}</strong><span>${esc(state.projects[0]?.localPath||'')}</span><a href="${esc(state.projects[0]?.githubUrl||'#')}" target="_blank" rel="noreferrer">Abrir GitHub ↗</a></div><h4>Puede hacer ahora</h4><ul><li>Revisar archivos y documentación</li><li>Consultar Git y rama activa</li><li>Ejecutar <code>npm test</code> si existe</li></ul><h4>Limitación actual</h4><p class="muted">El ejecutor Antigravity aún no está conectado. El chat no inventa cambios ni pruebas.</p></aside></div>`; }
function usePrompt(text){ const field=document.querySelector('.chat-composer textarea'); if(field){field.value=text;field.focus();} }
async function sendChat(e){ e.preventDefault(); const form=e.target; const field=form.elements.message; const message=field.value.trim(); if(!message)return; field.disabled=true; form.querySelector('button').disabled=true; const res=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message,projectId:state.projects[0]?.id})}); if(!res.ok){toast('No se pudo enviar el mensaje');field.disabled=false;form.querySelector('button').disabled=false;return;} field.value=''; await refresh('chat'); field.disabled=false;form.querySelector('button').disabled=false; document.querySelector('.chat-messages')?.scrollTo(0,99999); }
function render(name='chat'){ document.getElementById('page-title').textContent=titles[name]; view.innerHTML=name==='chat'?renderChat():name==='overview'?renderOverview():name==='tasks'?renderTasks():name==='projects'?renderProjects():renderActivity(); document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===name)); document.getElementById('task-count').textContent=state.tasks.filter(t=>t.status!=='completed').length; }
async function refresh(name){ const res=await fetch('/api/state'); state=await res.json(); const conversations=await fetch('/api/conversations'); const chat=await conversations.json(); state.messages=chat.messages||[]; document.getElementById('worker-name').textContent=state.worker.name; document.getElementById('repo-path').textContent=state.projects[0]?.localPath||'sin proyecto'; render(name); }
function navigate(name){ refresh(name); }
function toast(msg){ const el=document.getElementById('toast'); el.textContent=msg; el.classList.add('show'); setTimeout(()=>el.classList.remove('show'),2600); }
function closeModal(){ document.querySelector('.modal-backdrop')?.remove(); }
function openTaskModal(){ document.body.insertAdjacentHTML('beforeend',`<div class="modal-backdrop" onclick="if(event.target===this)closeModal()"><div class="modal"><div class="modal-head"><h2>Nueva solicitud al sistema</h2><button class="close" onclick="closeModal()">×</button></div><form onsubmit="submitTask(event)"><div class="field"><label>Qué necesitas</label><input name="title" placeholder="Ej: Revisar el proyecto" required autofocus></div><div class="field"><label>Contexto y criterios de aceptación</label><textarea name="description" placeholder="Ej: Revisa la estructura, pruebas, Git y riesgos. No modifiques archivos."></textarea></div><div class="field"><label>Prioridad</label><select name="priority"><option value="medium">Media</option><option value="high">Alta</option><option value="low">Baja</option></select></div><div class="modal-actions"><button type="button" class="secondary" onclick="closeModal()">Cancelar</button><button class="primary">Enviar solicitud</button></div></form></div></div>`); }
async function submitTask(e){ e.preventDefault(); const data=Object.fromEntries(new FormData(e.target)); const res=await fetch('/api/tasks',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}); if(res.ok){closeModal();toast('Tarea enviada al flujo de agentes');refresh('tasks');} }
function openProjectModal(){ document.body.insertAdjacentHTML('beforeend',`<div class="modal-backdrop" onclick="if(event.target===this)closeModal()"><div class="modal"><div class="modal-head"><h2>Conectar proyecto</h2><button class="close" onclick="closeModal()">×</button></div><form onsubmit="submitProject(event)"><div class="field"><label>Nombre del proyecto</label><input name="name" placeholder="Mi proyecto" required autofocus></div><div class="field"><label>Ruta local</label><input name="localPath" placeholder="/ruta/a/tu/repositorio"></div><div class="field"><label>Repositorio GitHub</label><input name="githubUrl" placeholder="github.com/organizacion/repositorio"></div><div class="field"><label>Rama principal</label><input name="branch" value="main"></div><div class="modal-actions"><button type="button" class="secondary" onclick="closeModal()">Cancelar</button><button class="primary">Conectar</button></div></form></div></div>`); }
async function submitProject(e){ e.preventDefault(); const data=Object.fromEntries(new FormData(e.target)); const res=await fetch('/api/projects',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}); if(res.ok){closeModal();toast('Proyecto conectado correctamente');refresh('projects');} }
document.querySelectorAll('.nav-item').forEach(b=>b.addEventListener('click',()=>navigate(b.dataset.view)));
document.addEventListener('keydown', e=>{ if(e.target.matches('.chat-composer textarea')&&e.key==='Enter'&&!e.shiftKey){e.preventDefault();e.target.form.requestSubmit();} });
refresh('chat'); setInterval(()=>refresh(document.querySelector('.nav-item.active')?.dataset.view||'chat'),3000);
